"""
Configuration file generator
"""

from typing import Optional, Dict, Any
from pathlib import Path
from datetime import timedelta

from .exceptions import ConfigFileError

class AirflowConfigGeneratorMixin:
    """Mixin with methods for generating configuration files"""
    
    def save(self, config_file: Optional[str] = None) -> None:
        """Save configuration to a .py file ready for Airflow"""
        output_file = config_file or self.config_file
        
        try:
            Path(output_file).parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_file, 'w', encoding='utf-8') as file:
                self._write_header(file)
                self._write_imports(file)
                self._write_variables(file)
                self._write_footer(file)
                
            print(f"✅ Configuration saved to: {output_file}")
                
        except Exception as e:
            raise ConfigFileError(f"Error saving Airflow config file: {e}")
    
    def _write_header(self, file) -> None:
        """Write file header"""
        file.write('"""\n')
        file.write('Airflow Variables Configuration\n')
        file.write('Generated by AirflowConfig\n')
        file.write('"""\n\n')
        
        file.write('# flake8: noqa\n')
        file.write('# type: ignore\n\n')
    
    def _write_imports(self, file) -> None:
        """Write necessary imports for Airflow"""
        file.write('import os\n')
        file.write('from datetime import timedelta\n')
        file.write('from airflow.models import Variable\n')
        file.write('\n')
        file.write('from airflow import DAG\n')
        file.write('from airflow.operators.python import PythonOperator\n')
        file.write('from airflow.operators.bash import BashOperator\n')
        file.write('\n')
    
    def _write_variables(self, file) -> None:
        """Write all variables with their default values"""
        sections = self._organize_variables_by_section()
        
        for section_name, section_vars in sections.items():
            if section_vars:
                file.write(f'\n# {self._default_sections.get(section_name, section_name.upper())}\n')
                file.write('#' + '=' * 50 + '\n')
                
                for var_name, var_value in section_vars.items():
                    if not var_name.startswith('__DOC_'):
                        doc_key = f'__DOC_{var_name}'
                        if doc_key in self.variables:
                            file.write(f'# {self.variables[doc_key]}\n')
                        
                        formatted_value = self._format_value_for_py(var_value)
                        file.write(f'{var_name} = {formatted_value}\n')
    
    def _organize_variables_by_section(self) -> Dict[str, Dict[str, Any]]:
        """Organize variables by sections"""
        sections = {section: {} for section in self._default_sections.keys()}
        sections['custom'] = {}
        
        for var_name, var_value in self.variables.items():
            if var_name.startswith('__DOC_'):
                continue
                
            section_found = False
            for section in self._default_sections.keys():
                if var_name.lower().startswith(section):
                    sections[section][var_name] = var_value
                    section_found = True
                    break
            
            if not section_found:
                sections['custom'][var_name] = var_value
        
        return sections
    
    def _format_value_for_py(self, value: Any) -> str:
        """Format values for Python"""
        if value is None:
            return "None"
        elif isinstance(value, bool):
            return "True" if value else "False"
        elif isinstance(value, (int, float)):
            return str(value)
        elif isinstance(value, str):
            return repr(value)
        elif isinstance(value, list):
            items = [self._format_value_for_py(item) for item in value]
            return f"[{', '.join(items)}]"
        elif isinstance(value, dict):
            items = [f"{repr(k)}: {self._format_value_for_py(v)}" for k, v in value.items()]
            return f"{{{', '.join(items)}}}"
        elif isinstance(value, timedelta):
            return f"timedelta(seconds={value.total_seconds()})"
        else:
            return repr(value)
    
    def _write_footer(self, file) -> None:
        """Write file footer with utility functions"""
        file.write('\n\n')
        file.write('def get_dag_default_args() -> dict:\n')
        file.write('    """Returns default arguments for DAGs"""\n')
        file.write('    return {\n')
        file.write("        'owner': AIRFLOW__DEFAULT__DAG_OWNER,\n")
        file.write("        'retries': AIRFLOW__CORE__DEFAULT_RETRIES,\n")
        file.write("        'retry_delay': timedelta(minutes=AIRFLOW__CORE__DEFAULT_RETRY_DELAY_MINUTES),\n")
        file.write("        'email_on_failure': True,\n")
        file.write("        'email_on_retry': False,\n")
        file.write("        'email': AIRFLOW__EMAIL__DEFAULT_EMAIL\n")
        file.write('    }\n')
        
        file.write('\n')
        file.write('def get_database_config() -> dict:\n')
        file.write('    """Returns database configuration"""\n')
        file.write('    return {\n')
        file.write("        'conn_id': AIRFLOW_DB_CONN_ID,\n")
        file.write("        'host': AIRFLOW_DB_HOST,\n")
        file.write("        'port': AIRFLOW_DB_PORT,\n")
        file.write("        'schema': AIRFLOW_DB_SCHEMA\n")
        file.write('    }\n')
        
        file.write('\n')
        file.write('def get_smtp_config() -> dict:\n')
        file.write('    """Returns SMTP configuration"""\n')
        file.write('    return {\n')
        file.write("        'smtp_host': AIRFLOW__SMTP__SMTP_HOST,\n")
        file.write("        'smtp_port': AIRFLOW__SMTP__SMTP_PORT,\n")
        file.write("        'smtp_user': AIRFLOW__SMTP__SMTP_USER,\n")
        file.write("        'smtp_password': AIRFLOW__SMTP__SMTP_PASSWORD\n")
        file.write('    }\n')
        
        file.write('\n')
        file.write('def get_variable_safely(var_name: str, default: Any = None) -> Any:\n')
        file.write('    """Safely get a variable with fallback to default"""\n')
        file.write('    try:\n')
        file.write('        return globals().get(var_name, default)\n')
        file.write('    except NameError:\n')
        file.write('        return default\n')